method: "bayes"
run_cap: 5

parameters:
  data_dir: ${embeddings_output_dir}
  n_samples: 10000
  batch_size: 256
  num_workers: [4, 8, 16, 32, 64]
  pin_memory: false
  prefetch_factor: [0, 2, 4, 8]
  shuffle: 5120
  shardshuffle: 32
