name: chromatin_accessibility
embedder: ${embedder} # used in trainer class
output_dir: ${output_dir} # used in trainer class

dataset:
  _target_: bend_hybrid.embedding.datasets.DataSupervised
  annotations_path: ${data_dir}/chromatin_accessibility/chromatin_accessibility.bed
  genome_path: ${data_dir}/genomes/GRCh37.no-chr.fa
  label_depth: 125
  sequence_length: 512
  # list of indices (0-based) of samples to exclude from dataset.
  # the following samples do not have valid sequences in the reference genome
  samples_to_exclude: [2062128]
  n_samples: null # Set to an integer to undersample the dataset
dataloaders:
  _target_: bend_hybrid.downstream.dataloaders.get_dataloaders
  shards_dir: ${embeddings_output_dir}
  batch_size: 256
  num_workers: 32
  prefetch_factor: 4
  padding_value: -100
  shuffle: 512
  shardshuffle: 32
model:
  _target_: bend_hybrid.downstream.model.Classifier
  input_size: ${embedding.${embedder}.embeddings_dim}
  output_size: ${task.dataset.label_depth}
  hidden_size: 64
  pooling: "swe" # Options: "default", "swe", "mean", "max", "mean_no_upsample"
  # only used for "default" pooling
  kernel_size: 3
  output_downsample_window: ${task.dataset.sequence_length}
  # only used for "swe" pooling
  freeze_swe: true
  num_ref_points: 100
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.003
  weight_decay: 0.01
params:
  epochs: 100
  load_checkpoint: false
  gradient_accumulation_steps: 1
  criterion: bce
  class_weights: null
  metric: auroc
  activation: none
