name: chromatin_accessibility
embedder: ${embedder} # used in trainer class
output_dir: ${output_dir} # used in trainer class

dataset:
  _target_: bend_hybrid.embedding.datasets.DataSupervised
  annotations_path: ${data_dir}/chromatin_accessibility/chromatin_accessibility.bed
  genome_path: ${data_dir}/genomes/GRCh37.no-chr.fa
  label_depth: 125
  sequence_length: 512
  # list of indices (0-based) of samples to exclude from dataset.
  # the following samples do not have valid sequences in the reference genome
  samples_to_exclude: [2062128]
  n_samples: null # Set to an integer to undersample the dataset
dataloaders:
  _target_: bend_hybrid.downstream.dataloaders.get_dataloaders
  shards_dir: ${embeddings_output_dir}
  batch_size: 256
  num_workers: 32
  prefetch_factor: 2
  padding_value: -100
  shuffle: 512
  shardshuffle: 32
model:
  _target_: bend_hybrid.models.downstream.CNN
  encoder: null
  input_size: ${embedding.${embedder}.embeddings_dim}
  output_size: ${task.dataset.label_depth}
  hidden_size: 64
  kernel_size: 3
pooling:
  location: input # Options: "input", "downstream"
  # If location is "input", pooling is applied to the embeddings before being passed to the downstream model.
  # If location is "downstream", pooling is applied in the downstream model, after the convolutional layers.
  mode: mean # Options: mean, max
  # If mean or max, the embeddings will be pooled across the sequence length dimension.
  # max is only supported when location is "input"
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.003
  weight_decay: 0.01
params:
  epochs: 100
  load_checkpoint: false
  gradient_accumulation_steps: 1
  criterion: bce
  class_weights: null
  metric: auroc
  activation: none
wandb:
  mode: disabled
