# @package _global_
defaults:
  - override /task: var_effects_expression
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe

hydra:
  mode: MULTIRUN
  sweeper:
    sampler:
      seed: 42
    direction: minimize
    study_name: var_effects_expression-${embedder}
    storage: null
    n_trials: 5
    n_jobs: 1
    params:
      task.dataloader.num_workers: choice(1, 2, 4, 8)
      task.dataloader.prefetch_factor: choice(0, 1, 2, 4)
  sweep:
    dir: ${output_dir}/sweep_${hydra.sweeper.study_name}
    subdir: ${now:%Y-%m-%d}_${hydra.job.num}

# Parameter only used in sweep, as var_effects tasks only have test set and undersampling would compromise results
n_samples: 25000 # undersample the dataset
