defaults:
  - embedding/embedders
  - task: gene_finding
  - _self_

hydra:
  searchpath:
    - file://config

# Specify only root directories
data_dir: ./data/ # Full data path specified in tasks/{task}.yml
embedders_dir: ./pretrained_models/ # Full embedding path specified in embedding/embedders.yml
embeddings_output_dir: ./data/embeddings/ # scripts will add /{task}/{embedder}
output_dir: ./results/ # scripts will add /{task}/{embedder}/

embedder: hyenadna-tiny-1k

wandb:
  project: bend-pooling-benchmark
