defaults:
  - embedding/embedders
  - task: gene_finding
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe
  - _self_

hydra:
  searchpath:
    - file://config

# Specify only root directories
data_dir: ./data/ # Full data path specified in tasks/{task}.yml
embedders_dir: ./pretrained_models/ # Full embedding path specified in embedding/embedders.yml
embeddings_output_dir: ./data/embeddings/ # scripts will add /{task}/{embedder}
output_dir: ./results/ # scripts will add /{task}/{embedder}/

embedder: nt_transformer_1000g

# supervised tasks only
compute_embeddings: true # Set to false to skip embedding computation
train_downstream: true # Set to false to skip training

n_samples: null # set to an integer for undersampling the dataset
