defaults:
  - embedding/embedders
  - task: gene_finding
  - _self_

hydra:
  searchpath:
    - file://config

# Specify only root directories
data_dir: ./data/ # Full data path specified in tasks/{task}.yml
embedders_dir: ./pretrained_models/ # Full embedding path specified in embedding/embedders.yml
embeddings_output_dir: ./data/embeddings/ # scripts will add /{task}/{embedder}
output_dir: ./results/ # scripts will add /{task}/{embedder}/

embedder: hyenadna-tiny-1k
max_shard_size: 3000000000 # max size of each shard in bytes

# supervised tasks only
pooling_mode: "none" # Options: "none", "mean", "max", "min-max", "mean_no_upsample"
