defaults:
  - embedding: embedders
  - tasks:
      [
        enhancer_annotation,
        chromatin_accessibility,
        gene_finding,
        histone_modification,
        cpg_methylation,
        var_effects_expression,
      ]
  - _self_
hydra:
  mode: MULTIRUN
  searchpath:
    - file://config
  sweeper:
    params:
      embedder: hyenadna-tiny-1k,
        hyenadna-large-1m,
        nt_transformer_ms,
        nt_transformer_1000g,
        nt_transformer_human_ref,
        nt_transformer_v2_500m,
        dnabert2,
        awdlstm,
        resnetlm
      task: gene_finding,
        enhancer_annotation,
        histone_modification,
        chromatin_accessibility,
        cpg_methylation,
        var_effects_expression

embedder: nt_transformer_1000g
task: gene_finding

work_dir: ./
data_dir: ${work_dir}/data/
embedders_dir: ${work_dir}/pretrained_models/
output_dir: ${work_dir}/results/ # Specify only the root output directory

chunk_size: 50000
chunk: null # can be given as a list of chunks to embed
