dnabert2:
  _target_: bend.utils.embedders.DNABert2Embedder
  model_name: zhihan1996/DNABERT-2-117M
  upsample_embeddings: true
hyenadna-large-1m:
  _target_: bend.utils.embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-large-1m-seqlen
  embeddings_dim: 256
hyenadna-tiny-1k:
  _target_: bend.utils.embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-tiny-1k-seqlen
  embeddings_dim: 128
resnetlm:
  _target_: bend.utils.embedders.ConvNetEmbedder
  model_path: ${embedders_dir}/convnet/
  embeddings_dim: 256
awdlstm:
  _target_: bend.utils.embedders.AWDLSTMEmbedder
  model_path: ${embedders_dir}/awd_lstm/
  embeddings_dim: 64
nt_transformer_ms:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  upsample_embeddings: true
  embeddings_dim: 2560
nt_transformer_human_ref:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-500m-human-ref
  upsample_embeddings: true
  embeddings_dim: 1280
nt_transformer_1000g:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-1000g
  upsample_embeddings: true
  embeddings_dim: 2560
nt_transformer_v2_500m:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-v2-500m-multi-species
  upsample_embeddings: true
  embeddings_dim: 1024
