dnabert2:
  _target_: bend_batch.embedding.embedders.dnabert2.DNABert2Embedder
  model_name: zhihan1996/DNABERT-2-117M
  upsample_embeddings: true
  embeddings_dim: 768
  autoregressive: false
  max_length: 10000 # https://github.com/Zhihan1996/DNABERT_2/issues/2
hyenadna-large-1m:
  _target_: bend_batch.embedding.embedders.hyenadna.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-large-1m-seqlen
  upsample_embeddings: false
  embeddings_dim: 256
  max_length: 1_000_002 # + 2 for special tokens
  autoregressive: true
hyenadna-tiny-1k:
  _target_: bend_batch.embedding.embedders.hyenadna.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-tiny-1k-seqlen
  upsample_embeddings: false
  embeddings_dim: 128
  max_length: 1026 # + 2 for special tokens
  autoregressive: true
resnetlm:
  _target_: bend_batch.embedding.embedders.resnetlm.ConvNetEmbedder
  model_path: ${embedders_dir}/convnet/
  upsample_embeddings: false
  embeddings_dim: 256
  max_length: null
  autoregressive: false
nt_transformer_ms:
  _target_: bend_batch.embedding.embedders.nt.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  upsample_embeddings: true
  embeddings_dim: 2560
  max_length: 1000
  autoregressive: false
nt_transformer_human_ref:
  _target_: bend_batch.embedding.embedders.nt.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-500m-human-ref
  upsample_embeddings: true
  embeddings_dim: 1280
  max_length: 1000
  autoregressive: false
nt_transformer_1000g:
  _target_: bend_batch.embedding.embedders.nt.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-1000g
  upsample_embeddings: true
  embeddings_dim: 2560
  max_length: 1000
  autoregressive: false
nt_transformer_v2_500m:
  _target_: bend_batch.embedding.embedders.nt.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-v2-500m-multi-species
  upsample_embeddings: true
  embeddings_dim: 1024
  max_length: 2048
  autoregressive: false
