embedders_dir: ${embedders_dir} # used in tests

dnabert2:
  _target_: bend.utils.batch_embedders.DNABert2Embedder
  model_name: zhihan1996/DNABERT-2-117M
  upsample_embeddings: true
  max_seq_len: 10000 # https://github.com/Zhihan1996/DNABERT_2/issues/2
hyenadna-large-1m:
  _target_: bend.utils.batch_embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-large-1m-seqlen
  max_seq_len: 1_000_000
hyenadna-tiny-1k:
  _target_: bend.utils.batch_embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-tiny-1k-seqlen
  max_seq_len: 1024
hyenadna-small-32k:
  _target_: bend.utils.batch_embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-small-32k-seqlen
  max_seq_len: 32768
hyenadna-medium-160k:
  _target_: bend.utils.batch_embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-medium-160k-seqlen
  max_seq_len: 160000
hyenadna-medium-450k:
  _target_: bend.utils.batch_embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-medium-450k-seqlen
  max_seq_len: 450000
resnetlm:
  _target_: bend.utils.batch_embedders.ConvNetEmbedder
  model_path: ${embedders_dir}/convnet/
  max_seq_len: null
awdlstm:
  _target_: bend.utils.batch_embedders.AWDLSTMEmbedder
  model_path: ${embedders_dir}/awd_lstm/
  max_seq_len: null
nt_transformer_ms:
  _target_: bend.utils.batch_embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  upsample_embeddings: true
  max_seq_len: 5994 # max_seq_len = token_len * len_single_token (6-mer) - EOS_token_len
  max_tokens_len: 1000
nt_transformer_human_ref:
  _target_: bend.utils.batch_embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-500m-human-ref
  upsample_embeddings: true
  max_seq_len: 5994 # max_seq_len = token_len * len_single_token (6-mer) - EOS_token_len
  max_tokens_len: 1000
nt_transformer_1000g:
  _target_: bend.utils.batch_embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-1000g
  upsample_embeddings: true
  max_seq_len: 5994 # max_seq_len = token_len * len_single_token (6-mer) - EOS_token_len
  max_tokens_len: 1000
nt_transformer_v2_500m:
  _target_: bend.utils.batch_embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-v2-500m-multi-species
  upsample_embeddings: true
  max_seq_len: 12282 # max_seq_len = token_len * len_single_token (6-mer) - EOS_token_len
  max_tokens_len: 2048
