dnabert2:
  _target_: bend.utils.embedders.DNABert2Embedder
  model_name: zhihan1996/DNABERT-2-117M
  upsample_embeddings: true
hyenadna-large-1m:
  _target_: bend.utils.embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-large-1m-seqlen
hyenadna-tiny-1k:
  _target_: bend.utils.embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-tiny-1k-seqlen
hyenadna-small-32k:
  _target_: bend.utils.embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-small-32k-seqlen
hyenadna-medium-160k:
  _target_: bend.utils.embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-medium-160k-seqlen
hyenadna-medium-450k:
  _target_: bend.utils.embedders.HyenaDNAEmbedder
  model_path: ${embedders_dir}/hyenadna/hyenadna-medium-450k-seqlen
resnetlm:
  _target_: bend.utils.embedders.ConvNetEmbedder
  model_path: ${embedders_dir}/convnet/
awdlstm:
  _target_: bend.utils.embedders.AWDLSTMEmbedder
  model_path: ${embedders_dir}/awd_lstm/
nt_transformer_ms:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  upsample_embeddings: true
nt_transformer_human_ref:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-500m-human-ref
  upsample_embeddings: true
nt_transformer_1000g:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-2.5b-1000g
  upsample_embeddings: true
nt_transformer_v2_500m:
  _target_: bend.utils.embedders.NucleotideTransformerEmbedder
  model_name: InstaDeepAI/nucleotide-transformer-v2-500m-multi-species
  upsample_embeddings: true
